swagger: "2.0"
info:
  version: "1.0.0"
  title: Brokering Portfolio
host: localhost:3000
basepath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users/assetList:
    get:
      description: Returns a user based on a single ID, if the user does not have access to the pet
      operationId: findPetById
      produces:
        - application/json
        - application/xml
        - text/xml
        - text/html
      parameters:
        - name: id
          in: query
          description: ID of pet to fetch
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: pet response
        default:
          description: unexpected error


  /hello_world/hello/{id}:
  # binds a127 app logic to a route
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      consumes:
        - application/json
      produces:
        - application/json
        - application/xml      
      parameters:
        - name: id
          in: path
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          #schema:
            # a pointer to a definition
            #$ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          #schema:
            #$ref: "#/definitions/ErrorResponse"